import { CVMetadata } from "../entities/cv-metadata";
import { ValidationException } from "../../../../common/exceptions/validation-exception";

/**
 * Input data required to create a new CVMetadata via CVMetadataFactory.
 */
export interface CreateCVMetadataInput {
  /** The ID of the student who owns this CV. */
  studentId: string;
  /** System-assigned file name (e.g. UUID-based). */
  fileName: string;
  /** Original file name as uploaded by the student. */
  originalFileName: string;
  /** MIME type of the uploaded file (e.g. "application/pdf"). */
  mimeType: string;
  /** File size in bytes. */
  fileSize: number;
  /** Storage path where the file is physically stored. */
  storagePath: string;
}

/**
 * Factory for creating CVMetadata domain entities.
 *
 * ═══════════════════════════════════════════════════════════════════
 * FACTORY PATTERN
 * ═══════════════════════════════════════════════════════════════════
 *
 * The Factory pattern centralises the creation of domain objects,
 * encapsulating construction logic that would otherwise be scattered
 * across the application layer. This ensures every CVMetadata entity
 * is created in a consistent, valid state.
 *
 * ═══════════════════════════════════════════════════════════════════
 * RESPONSIBILITIES
 * ═══════════════════════════════════════════════════════════════════
 *
 * 1. Validate Construction Invariants (studentId, fileName,
 *    originalFileName, mimeType, fileSize, storagePath).
 * 2. Set sensible defaults for optional fields (id, isDefault,
 *    uploadedAt, updatedAt).
 * 3. Return a fully constructed CVMetadata entity.
 *
 * ═══════════════════════════════════════════════════════════════════
 * CONSTRUCTION INVARIANTS
 * ═══════════════════════════════════════════════════════════════════
 *
 * Construction Invariants are the minimum structural requirements
 * that must be satisfied for an object to be created at all:
 *
 *   - studentId must be a non-empty string
 *   - fileName must be a non-empty string
 *   - originalFileName must be a non-empty string
 *   - mimeType must be a non-empty string
 *   - fileSize must be > 0
 *   - storagePath must be a non-empty string
 *
 * These are separate from Business Rules, which are the domain
 * policies that govern whether an operation is semantically valid.
 *
 * ═══════════════════════════════════════════════════════════════════
 * PERSISTENCE BELONGS TO REPOSITORY
 * ═══════════════════════════════════════════════════════════════════
 *
 * The factory does NOT access the database, call any Repository,
 * or check for duplicates. Persistence concerns are handled by the
 * Repository in the Infrastructure Layer.
 *
 * ═══════════════════════════════════════════════════════════════════
 * BUSINESS RULES BELONG TO USECASE
 * ═══════════════════════════════════════════════════════════════════
 *
 * The following rules are NOT validated in this factory:
 *   - Student existence
 *   - Upload quotas / max upload limits
 *   - Virus scanning
 *   - Duplicate filename
 *   - Duplicate hash
 *   - Permission checks
 *   - Default uniqueness
 *
 * These are business flow concerns that belong to the Application
 * Layer (Use Cases), where access to Repositories and external
 * services is available.
 *
 * ═══════════════════════════════════════════════════════════════════
 *
 * @category Domain Factory
 */
export class CVMetadataFactory {
  /**
   * Create a new CVMetadata domain entity.
   *
   * The factory sets the following default values:
   *   - `id` = `null` (generated by the database on first save)
   *   - `isDefault` = `false`
   *   - `uploadedAt` = current timestamp
   *   - `updatedAt` = current timestamp
   *
   * @param input - The data required to create the CV metadata.
   * @returns A fully constructed CVMetadata entity.
   * @throws {ValidationException} If input validation fails.
   */
  create(input: CreateCVMetadataInput): CVMetadata {
    this.validateInput(input);

    const now = new Date();

    return new CVMetadata({
      id: null,
      studentId: input.studentId,
      fileName: input.fileName,
      originalFileName: input.originalFileName,
      mimeType: input.mimeType,
      fileSize: input.fileSize,
      storagePath: input.storagePath,
      isDefault: false,
      uploadedAt: now,
      updatedAt: now,
    });
  }

  /**
   * Validate the Construction Invariants before creating a CVMetadata entity.
   *
   * Factory only validates structural requirements necessary to create
   * a valid entity. Business rules (e.g. student existence, duplicate
   * checking, quota enforcement) are validated by the Application Layer.
   *
   * @param input - The input data to validate.
   * @throws {ValidationException} If any required field is missing or invalid.
   */
  private validateInput(input: CreateCVMetadataInput): void {
    if (!input.studentId || input.studentId.trim().length === 0) {
      throw new ValidationException("studentId is required");
    }

    if (!input.fileName || input.fileName.trim().length === 0) {
      throw new ValidationException("fileName is required");
    }

    if (!input.originalFileName || input.originalFileName.trim().length === 0) {
      throw new ValidationException("originalFileName is required");
    }

    if (!input.mimeType || input.mimeType.trim().length === 0) {
      throw new ValidationException("mimeType is required");
    }

    if (!input.storagePath || input.storagePath.trim().length === 0) {
      throw new ValidationException("storagePath is required");
    }

    if (input.fileSize <= 0) {
      throw new ValidationException("fileSize must be greater than 0");
    }
  }
}
