/**
 * JobPosting domain entity — Rich Domain Model with State Machine.
 *
 * ═══════════════════════════════════════════════════════════════════
 * WHY RICH DOMAIN MODEL?
 * ═══════════════════════════════════════════════════════════════════
 *
 * Business rules that govern JobPosting state transitions are
 * encapsulated inside the entity itself rather than scattered across
 * Use Cases. This prevents anemic domain models and ensures
 * consistency: every code path that changes job posting state
 * goes through the same validation, transition logic, and updatedAt
 * management.
 *
 * ═══════════════════════════════════════════════════════════════════
 * STATE MACHINE
 * ═══════════════════════════════════════════════════════════════════
 *
 *   DRAFT ───────── submittedForApproval ──→ PENDING
 *   PENDING ─────── approve ───────────────→ APPROVED
 *   PENDING ─────── reject ────────────────→ REJECTED
 *   REJECTED ────── reopen ────────────────→ DRAFT
 *   APPROVED ────── close ─────────────────→ CLOSED
 *   APPROVED ────── expire ────────────────→ EXPIRED
 *
 * Each business method self-validates its allowed source state
 * directly — no global transition table is used.
 *
 * ═══════════════════════════════════════════════════════════════════
 * IMMUTABILITY NOTE
 * ═══════════════════════════════════════════════════════════════════
 *
 * Fields are private and only exposed via getters. State mutations
 * are performed exclusively through explicit business methods
 * (submitForApproval, approve, reject, etc.) which validate the
 * transition and update `updatedAt` automatically.
 *
 * ═══════════════════════════════════════════════════════════════════
 *
 * @category Domain Entity
 */

import { ConflictException } from "../../../common/exceptions/conflict-exception";
import { ValidationException } from "../../../common/exceptions/validation-exception";

/**
 * Possible states for a JobPosting.
 *
 * These represent the lifecycle of a job posting from creation
 * through approval, closing, or expiration.
 */
export enum JobPostingState {
  /** Initial state after creation. Not yet submitted for review. */
  DRAFT = "DRAFT",
  /** Submitted for approval, awaiting review. */
  PENDING = "PENDING",
  /** Approved and visible to candidates. */
  APPROVED = "APPROVED",
  /** Rejected during review. Can be reopened (→ DRAFT) for editing. */
  REJECTED = "REJECTED",
  /** Manually closed by the employer. Terminal state. */
  CLOSED = "CLOSED",
  /** Automatically expired after the posting period ended. Terminal state. */
  EXPIRED = "EXPIRED",
}

/**
 * Properties required to construct a JobPosting entity.
 *
 * The `id` field is `string | null` because the entity may be created
 * before persistence (e.g. by JobPostingFactory). The actual ID
 * is generated by the database (Prisma cuid) when the entity is first
 * saved.
 */
export interface JobPostingProps {
  id: string | null;
  employerId: string;
  title: string;
  description: string;
  requirements: string;
  salaryMin: number | null;
  salaryMax: number | null;
  currency: string;
  location: string;
  state: JobPostingState;
  approvedAt: Date | null;
  approvedBy: string | null;
  rejectionReason: string | null;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class JobPosting {
  private _id: string | null;
  private _employerId: string;
  private _title: string;
  private _description: string;
  private _requirements: string;
  private _salaryMin: number | null;
  private _salaryMax: number | null;
  private _currency: string;
  private _location: string;
  private _state: JobPostingState;
  private _approvedAt: Date | null;
  private _approvedBy: string | null;
  private _rejectionReason: string | null;
  private _expiresAt: Date;
  private _createdAt: Date;
  private _updatedAt: Date;

  constructor(props: JobPostingProps) {
    this._id = props.id;
    this._employerId = props.employerId;
    this._title = props.title;
    this._description = props.description;
    this._requirements = props.requirements;
    this._salaryMin = props.salaryMin;
    this._salaryMax = props.salaryMax;
    this._currency = props.currency;
    this._location = props.location;
    this._state = props.state;
    this._approvedAt = props.approvedAt;
    this._approvedBy = props.approvedBy;
    this._rejectionReason = props.rejectionReason;
    this._expiresAt = props.expiresAt;
    this._createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  // ── Getters ──────────────────────────────────────────────────────

  get id(): string | null {
    return this._id;
  }

  get employerId(): string {
    return this._employerId;
  }

  get title(): string {
    return this._title;
  }

  get description(): string {
    return this._description;
  }

  get requirements(): string {
    return this._requirements;
  }

  get salaryMin(): number | null {
    return this._salaryMin;
  }

  get salaryMax(): number | null {
    return this._salaryMax;
  }

  get currency(): string {
    return this._currency;
  }

  get location(): string {
    return this._location;
  }

  get state(): JobPostingState {
    return this._state;
  }

  get approvedAt(): Date | null {
    return this._approvedAt;
  }

  get approvedBy(): string | null {
    return this._approvedBy;
  }

  get rejectionReason(): string | null {
    return this._rejectionReason;
  }

  get expiresAt(): Date {
    return this._expiresAt;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  // ── Business methods — State transitions ─────────────────────────

  /**
   * Submit the job posting for approval.
   *
   * Transitions: DRAFT → PENDING
   *
   * @throws {ConflictException} If the current state is not DRAFT.
   */
  submitForApproval(): void {
    if (this._state !== JobPostingState.DRAFT) {
      throw new ConflictException(
        `Cannot submit for approval: current state is ${this._state}, expected DRAFT`,
      );
    }
    this._state = JobPostingState.PENDING;
    this._updatedAt = new Date();
  }

  /**
   * Approve the job posting.
   *
   * Transitions: PENDING → APPROVED
   *
   * @param approvedBy - The ID of the user who approved this posting.
   * @throws {ConflictException} If the current state is not PENDING.
   */
  approve(approvedBy: string): void {
    if (this._state !== JobPostingState.PENDING) {
      throw new ConflictException(
        `Cannot approve: current state is ${this._state}, expected PENDING`,
      );
    }
    this._state = JobPostingState.APPROVED;
    this._approvedAt = new Date();
    this._approvedBy = approvedBy;
    this._rejectionReason = null;
    this._updatedAt = new Date();
  }

  /**
   * Reject the job posting.
   *
   * Transitions: PENDING → REJECTED
   *
   * @param reason - The reason for rejection.
   * @throws {ConflictException} If the current state is not PENDING.
   */
  reject(reason: string): void {
    if (this._state !== JobPostingState.PENDING) {
      throw new ConflictException(
        `Cannot reject: current state is ${this._state}, expected PENDING`,
      );
    }
    this._state = JobPostingState.REJECTED;
    this._rejectionReason = reason;
    this._approvedAt = null;
    this._approvedBy = null;
    this._updatedAt = new Date();
  }

  /**
   * Close the job posting (e.g. position filled, no longer accepting
   * applications).
   *
   * Transitions: APPROVED → CLOSED
   *
   * @throws {ConflictException} If the current state is not APPROVED.
   */
  close(): void {
    if (this._state !== JobPostingState.APPROVED) {
      throw new ConflictException(
        `Cannot close: current state is ${this._state}, expected APPROVED`,
      );
    }
    this._state = JobPostingState.CLOSED;
    this._updatedAt = new Date();
  }

  /**
   * Reopen a rejected job posting for editing and resubmission.
   *
   * Transitions: REJECTED → DRAFT
   *
   * @throws {ConflictException} If the current state is not REJECTED.
   */
  reopen(): void {
    if (this._state !== JobPostingState.REJECTED) {
      throw new ConflictException(
        `Cannot reopen: current state is ${this._state}, expected REJECTED`,
      );
    }
    this._state = JobPostingState.DRAFT;
    this._rejectionReason = null;
    this._updatedAt = new Date();
  }

  /**
   * Mark the job posting as expired.
   *
   * Transitions: APPROVED → EXPIRED
   *
   * @throws {ConflictException} If the current state is not APPROVED.
   */
  expire(): void {
    if (this._state !== JobPostingState.APPROVED) {
      throw new ConflictException(
        `Cannot expire: current state is ${this._state}, expected APPROVED`,
      );
    }
    this._state = JobPostingState.EXPIRED;
    this._updatedAt = new Date();
  }

  // ── Business methods — Field updates with validation ─────────────

  /**
   * Update the title of the job posting.
   *
   * @param title - The new title. Must not be empty and must not
   *                exceed 120 characters.
   * @throws {ValidationException} If validation fails.
   */
  updateTitle(title: string): void {
    if (!title || title.trim().length === 0) {
      throw new ValidationException("title is required");
    }
    if (title.length > 120) {
      throw new ValidationException("title must not exceed 120 characters");
    }
    this._title = title;
    this._updatedAt = new Date();
  }

  /**
   * Update the description of the job posting.
   *
   * @param description - The new description. Must not be empty.
   * @throws {ValidationException} If validation fails.
   */
  updateDescription(description: string): void {
    if (!description || description.trim().length === 0) {
      throw new ValidationException("description is required");
    }
    this._description = description;
    this._updatedAt = new Date();
  }

  /**
   * Update the requirements of the job posting.
   *
   * @param requirements - The new requirements.
   */
  updateRequirements(requirements: string): void {
    this._requirements = requirements;
    this._updatedAt = new Date();
  }

  /**
   * Update the salary range of the job posting.
   *
   * @param salaryMin - The minimum salary (nullable).
   * @param salaryMax - The maximum salary (nullable).
   * @throws {ValidationException} If salaryMin > salaryMax (when both
   *                               are non-null).
   */
  updateSalaryRange(salaryMin: number | null, salaryMax: number | null): void {
    if (salaryMin !== null && salaryMax !== null && salaryMin > salaryMax) {
      throw new ValidationException("salaryMin must not exceed salaryMax");
    }
    this._salaryMin = salaryMin;
    this._salaryMax = salaryMax;
    this._updatedAt = new Date();
  }

  /**
   * Update the location of the job posting.
   *
   * @param location - The new location.
   */
  updateLocation(location: string): void {
    this._location = location;
    this._updatedAt = new Date();
  }

  /**
   * Update the expiration date of the job posting.
   *
   * @param expiresAt - The new expiration date. Must be in the future.
   * @throws {ValidationException} If expiresAt is not after the
   *                               current time.
   */
  updateExpiresAt(expiresAt: Date): void {
    if (!expiresAt || expiresAt <= new Date()) {
      throw new ValidationException("expiresAt must be in the future");
    }
    this._expiresAt = expiresAt;
    this._updatedAt = new Date();
  }
}
