/**
 * Application domain entity — Rich Domain Model with State Machine.
 *
 * ═══════════════════════════════════════════════════════════════════
 * WHY RICH DOMAIN MODEL?
 * ═══════════════════════════════════════════════════════════════════
 *
 * Business rules that govern Application state transitions are
 * encapsulated inside the entity itself rather than scattered across
 * Use Cases. This prevents anemic domain models and ensures
 * consistency: every code path that changes application state
 * goes through the same validation, transition logic, and updatedAt
 * management.
 *
 * ═══════════════════════════════════════════════════════════════════
 * STATE MACHINE
 * ═══════════════════════════════════════════════════════════════════
 *
 *   APPLIED ────── review ──────────────→ UNDER_REVIEW
 *   UNDER_REVIEW ── accept ─────────────→ ACCEPTED
 *   APPLIED ────── reject ──────────────→ REJECTED
 *   UNDER_REVIEW ── reject ─────────────→ REJECTED
 *   APPLIED ────── withdraw ────────────→ WITHDRAWN
 *   UNDER_REVIEW ── withdraw ───────────→ WITHDRAWN
 *
 * Each business method self-validates its allowed source state
 * via the ApplicationState Value Object.
 *
 * ═══════════════════════════════════════════════════════════════════
 * IMMUTABILITY NOTE
 * ═══════════════════════════════════════════════════════════════════
 *
 * Fields are private and only exposed via getters. State mutations
 * are performed exclusively through explicit business methods
 * (review, accept, reject, withdraw) which validate the transition
 * and update `updatedAt` automatically.
 *
 * ═══════════════════════════════════════════════════════════════════
 *
 * @category Domain Entity
 */

import { ConflictException } from "../../../../common/exceptions/conflict-exception";
import { ValidationException } from "../../../../common/exceptions/validation-exception";
import { ApplicationState } from "../value-objects/application-state";

/**
 * Properties required to construct an Application entity.
 *
 * The `id` field is `string | null` because the entity may be created
 * before persistence (e.g. by ApplicationFactory). The actual ID
 * is generated by the database (Prisma cuid) when the entity is first
 * saved.
 */
export interface ApplicationProps {
  id: string | null;
  studentId: string;
  jobPostingId: string;
  cvId: string;
  state: ApplicationState;
  rejectionReason: string | null;
  appliedAt: Date;
  reviewedAt: Date | null;
  reviewedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export class Application {
  private _id: string | null;
  private _studentId: string;
  private _jobPostingId: string;
  private _cvId: string;
  private _state: ApplicationState;
  private _rejectionReason: string | null;
  private _appliedAt: Date;
  private _reviewedAt: Date | null;
  private _reviewedBy: string | null;
  private _createdAt: Date;
  private _updatedAt: Date;

  constructor(props: ApplicationProps) {
    this._id = props.id;
    this._studentId = props.studentId;
    this._jobPostingId = props.jobPostingId;
    this._cvId = props.cvId;
    this._state = props.state;
    this._rejectionReason = props.rejectionReason;
    this._appliedAt = props.appliedAt;
    this._reviewedAt = props.reviewedAt;
    this._reviewedBy = props.reviewedBy;
    this._createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  // ── Getters ──────────────────────────────────────────────────────

  get id(): string | null {
    return this._id;
  }

  get studentId(): string {
    return this._studentId;
  }

  get jobPostingId(): string {
    return this._jobPostingId;
  }

  get cvId(): string {
    return this._cvId;
  }

  get state(): ApplicationState {
    return this._state;
  }

  get rejectionReason(): string | null {
    return this._rejectionReason;
  }

  get appliedAt(): Date {
    return this._appliedAt;
  }

  get reviewedAt(): Date | null {
    return this._reviewedAt;
  }

  get reviewedBy(): string | null {
    return this._reviewedBy;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  // ── Business methods — State transitions ─────────────────────────

  /**
   * Move the application to UNDER_REVIEW.
   *
   * Transitions: APPLIED → UNDER_REVIEW
   *
   * @param reviewedBy - The ID of the reviewer (employer).
   * @throws {ConflictException} If the current state does not allow review.
   * @throws {ValidationException} If reviewedBy is empty.
   */
  review(reviewedBy: string): void {
    if (!this._state.canReview()) {
      throw new ConflictException(
        `Cannot review: current state is ${this._state}, expected APPLIED`,
      );
    }
    if (!reviewedBy || reviewedBy.trim().length === 0) {
      throw new ValidationException("reviewedBy is required");
    }
    this._state = ApplicationState.underReview();
    this._reviewedAt = new Date();
    this._reviewedBy = reviewedBy;
    this._updatedAt = new Date();
  }

  /**
   * Accept the application.
   *
   * Transitions: UNDER_REVIEW → ACCEPTED
   *
   * @throws {ConflictException} If the current state does not allow acceptance.
   */
  accept(): void {
    if (!this._state.canAccept()) {
      throw new ConflictException(
        `Cannot accept: current state is ${this._state}, expected UNDER_REVIEW`,
      );
    }
    this._state = ApplicationState.accepted();
    this._updatedAt = new Date();
  }

  /**
   * Reject the application.
   *
   * Transitions:
   *   - APPLIED → REJECTED
   *   - UNDER_REVIEW → REJECTED
   *
   * @param reason - The reason for rejection.
   * @throws {ConflictException} If the current state does not allow rejection.
   * @throws {ValidationException} If reason is empty.
   */
  reject(reason: string): void {
    if (!this._state.canReject()) {
      throw new ConflictException(
        `Cannot reject: current state is ${this._state}, expected APPLIED or UNDER_REVIEW`,
      );
    }
    if (!reason || reason.trim().length === 0) {
      throw new ValidationException("rejection reason is required");
    }
    this._state = ApplicationState.rejected();
    this._rejectionReason = reason;
    this._updatedAt = new Date();
  }

  /**
   * Withdraw the application.
   *
   * Transitions:
   *   - APPLIED → WITHDRAWN
   *   - UNDER_REVIEW → WITHDRAWN
   *
   * @throws {ConflictException} If the current state does not allow withdrawal.
   */
  withdraw(): void {
    if (!this._state.canWithdraw()) {
      throw new ConflictException(
        `Cannot withdraw: current state is ${this._state}, expected APPLIED or UNDER_REVIEW`,
      );
    }
    this._state = ApplicationState.withdrawn();
    this._updatedAt = new Date();
  }

  // ── Business methods — Field updates ─────────────────────────────

  /**
   * Change the CV attached to this application.
   *
   * @param cvId - The new CV ID. Must not be empty.
   * @throws {ValidationException} If cvId is empty.
   */
  changeCv(cvId: string): void {
    if (!cvId || cvId.trim().length === 0) {
      throw new ValidationException("cvId is required");
    }
    this._cvId = cvId;
    this._updatedAt = new Date();
  }
}
