/**
 * JobPosting domain entity — Rich Domain Model with State Machine.
 *
 * ═══════════════════════════════════════════════════════════════════
 * WHY RICH DOMAIN MODEL?
 * ═══════════════════════════════════════════════════════════════════
 *
 * Business rules that govern JobPosting state transitions are
 * encapsulated inside the entity itself rather than scattered across
 * Use Cases. This prevents anemic domain models and ensures
 * consistency: every code path that changes job posting state
 * goes through the same validation, transition logic, and updatedAt
 * management.
 *
 * ═══════════════════════════════════════════════════════════════════
 * STATE MACHINE
 * ═══════════════════════════════════════════════════════════════════
 *
 *   DRAFT ────────── submit ───────────→ SUBMITTED
 *   SUBMITTED ────── approve ──────────→ APPROVED
 *   SUBMITTED ────── reject ───────────→ REJECTED
 *   REJECTED ─────── reopen ───────────→ DRAFT
 *   APPROVED ─────── close ────────────→ CLOSED
 *
 * Each business method self-validates its allowed source state
 * directly via JobState transition validation methods.
 *
 * ═══════════════════════════════════════════════════════════════════
 * IMMUTABILITY NOTE
 * ═══════════════════════════════════════════════════════════════════
 *
 * Fields are private and only exposed via getters. State mutations
 * are performed exclusively through explicit business methods
 * (submit, approve, reject, reopen, close) which validate the
 * transition and update `updatedAt` automatically.
 *
 * ═══════════════════════════════════════════════════════════════════
 * CONSTRUCTION INVARIANTS
 * ═══════════════════════════════════════════════════════════════════
 *
 * Validated in constructor:
 * - employerId: must not be empty
 * - title: must not be empty and must not exceed 120 characters
 * - description: must not be empty
 * - requirements: must not be empty
 * - location: must not be empty
 * - expiresAt: must be in the future
 * - salaryMin: if provided, must be >= 0
 * - salaryMax: if provided, must be >= 0
 * - salaryMin and salaryMax: if both provided, salaryMin <= salaryMax
 * - createdAt: must not be null
 * - updatedAt: must not be null
 *
 * Violation throws ValidationException.
 *
 * ═══════════════════════════════════════════════════════════════════
 * BUSINESS METHODS
 * ═══════════════════════════════════════════════════════════════════
 *
 * submit()                       - DRAFT → SUBMITTED
 * approve(approvedBy)            - SUBMITTED → APPROVED
 * reject(reason)                 - SUBMITTED → REJECTED
 * reopen()                       - REJECTED → DRAFT
 * close()                        - APPROVED → CLOSED
 * updateTitle(title)             - Updates title with validation
 * updateDescription(description) - Updates description with validation
 * updateRequirements(reqs)       - Updates requirements
 * updateSalaryRange(min, max)    - Updates salary range
 * updateLocation(location)       - Updates location
 * updateExpiresAt(date)          - Updates expiration date
 *
 * No public setters. No new object returned.
 *
 * @category Domain Entity
 */

import { ValidationException } from "../../../../common/exceptions/validation-exception";
import { ConflictException } from "../../../../common/exceptions/conflict-exception";
import { JobState, type JobStateValue } from "../value-objects/job-state";

/**
 * Properties required to construct a JobPosting entity.
 *
 * The `id` field is `string | null` because the entity may be created
 * before persistence (e.g. by JobPostingFactory). The actual ID
 * is generated by the database (Prisma cuid) when the entity is first
 * saved.
 */
export interface JobPostingProps {
  id: string | null;
  employerId: string;
  title: string;
  description: string;
  requirements: string;
  salaryMin: number | null;
  salaryMax: number | null;
  currency: string;
  location: string;
  state: JobStateValue;
  approvedAt: Date | null;
  approvedBy: string | null;
  rejectionReason: string | null;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class JobPosting {
  private _id: string | null;
  private _employerId: string;
  private _title: string;
  private _description: string;
  private _requirements: string;
  private _salaryMin: number | null;
  private _salaryMax: number | null;
  private _currency: string;
  private _location: string;
  private _state: JobState;
  private _approvedAt: Date | null;
  private _approvedBy: string | null;
  private _rejectionReason: string | null;
  private _expiresAt: Date;
  private _createdAt: Date;
  private _updatedAt: Date;

  constructor(props: JobPostingProps) {
    // ── Construction Invariants ──────────────────────────────────

    if (!props.employerId || props.employerId.trim() === "") {
      throw new ValidationException("employerId must not be empty");
    }
    if (!props.title || props.title.trim() === "") {
      throw new ValidationException("title must not be empty");
    }
    if (props.title && props.title.length > 120) {
      throw new ValidationException("title must not exceed 120 characters");
    }
    if (!props.description || props.description.trim() === "") {
      throw new ValidationException("description must not be empty");
    }
    if (!props.requirements || props.requirements.trim() === "") {
      throw new ValidationException("requirements must not be empty");
    }
    if (!props.location || props.location.trim() === "") {
      throw new ValidationException("location must not be empty");
    }
    if (props.salaryMin !== null && props.salaryMin !== undefined && props.salaryMin < 0) {
      throw new ValidationException("salaryMin must not be negative");
    }
    if (props.salaryMax !== null && props.salaryMax !== undefined && props.salaryMax < 0) {
      throw new ValidationException("salaryMax must not be negative");
    }
    if (props.salaryMin !== null && props.salaryMax !== null && props.salaryMin > props.salaryMax) {
      throw new ValidationException("salaryMin must not exceed salaryMax");
    }
    if (props.createdAt === null || props.createdAt === undefined) {
      throw new ValidationException("createdAt must not be null");
    }
    if (props.updatedAt === null || props.updatedAt === undefined) {
      throw new ValidationException("updatedAt must not be null");
    }

    this._id = props.id;
    this._employerId = props.employerId;
    this._title = props.title;
    this._description = props.description;
    this._requirements = props.requirements;
    this._salaryMin = props.salaryMin;
    this._salaryMax = props.salaryMax;
    this._currency = props.currency;
    this._location = props.location;
    this._state = new JobState(props.state);
    this._approvedAt = props.approvedAt;
    this._approvedBy = props.approvedBy;
    this._rejectionReason = props.rejectionReason;
    this._expiresAt = props.expiresAt;
    this._createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  // ── Getters ──────────────────────────────────────────────────────

  get id(): string | null {
    return this._id;
  }

  get employerId(): string {
    return this._employerId;
  }

  get title(): string {
    return this._title;
  }

  get description(): string {
    return this._description;
  }

  get requirements(): string {
    return this._requirements;
  }

  get salaryMin(): number | null {
    return this._salaryMin;
  }

  get salaryMax(): number | null {
    return this._salaryMax;
  }

  get currency(): string {
    return this._currency;
  }

  get location(): string {
    return this._location;
  }

  get state(): JobState {
    return this._state;
  }

  get approvedAt(): Date | null {
    return this._approvedAt;
  }

  get approvedBy(): string | null {
    return this._approvedBy;
  }

  get rejectionReason(): string | null {
    return this._rejectionReason;
  }

  get expiresAt(): Date {
    return this._expiresAt;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  // ── Business methods — State transitions ─────────────────────────

  /**
   * Submit the job posting for approval.
   *
   * Transitions: DRAFT → SUBMITTED
   *
   * @throws {ConflictException} If the current state is not DRAFT.
   */
  submit(): void {
    if (!this._state.canSubmit()) {
      throw new ConflictException(
        `Cannot submit for approval: current state is ${this._state}, expected DRAFT`,
      );
    }
    this._state = JobState.submitted();
    this._updatedAt = new Date();
  }

  /**
   * Approve the job posting.
   *
   * Transitions: SUBMITTED → APPROVED
   *
   * @param approvedBy - The ID of the user who approved this posting.
   * @throws {ConflictException} If the current state is not SUBMITTED.
   */
  approve(approvedBy: string): void {
    if (!this._state.canApprove()) {
      throw new ConflictException(
        `Cannot approve: current state is ${this._state}, expected SUBMITTED`,
      );
    }
    this._state = JobState.approved();
    this._approvedAt = new Date();
    this._approvedBy = approvedBy;
    this._rejectionReason = null;
    this._updatedAt = new Date();
  }

  /**
   * Reject the job posting.
   *
   * Transitions: SUBMITTED → REJECTED
   *
   * @param reason - The reason for rejection.
   * @throws {ConflictException} If the current state is not SUBMITTED.
   */
  reject(reason: string): void {
    if (!this._state.canReject()) {
      throw new ConflictException(
        `Cannot reject: current state is ${this._state}, expected SUBMITTED`,
      );
    }
    this._state = JobState.rejected();
    this._rejectionReason = reason;
    this._approvedAt = null;
    this._approvedBy = null;
    this._updatedAt = new Date();
  }

  /**
   * Reopen a rejected job posting for editing and resubmission.
   *
   * Transitions: REJECTED → DRAFT
   *
   * @throws {ConflictException} If the current state is not REJECTED.
   */
  reopen(): void {
    if (!this._state.canReopen()) {
      throw new ConflictException(
        `Cannot reopen: current state is ${this._state}, expected REJECTED`,
      );
    }
    this._state = JobState.draft();
    this._rejectionReason = null;
    this._updatedAt = new Date();
  }

  /**
   * Close the job posting (e.g. position filled, no longer accepting
   * applications).
   *
   * Transitions: APPROVED → CLOSED
   *
   * @throws {ConflictException} If the current state is not APPROVED.
   */
  close(): void {
    if (!this._state.canClose()) {
      throw new ConflictException(
        `Cannot close: current state is ${this._state}, expected APPROVED`,
      );
    }
    this._state = JobState.closed();
    this._updatedAt = new Date();
  }

  // ── Business methods — Field updates with validation ─────────────

  /**
   * Update the title of the job posting.
   *
   * @param title - The new title. Must not be empty and must not
   *                exceed 120 characters.
   * @throws {ValidationException} If validation fails.
   */
  updateTitle(title: string): void {
    if (!title || title.trim().length === 0) {
      throw new ValidationException("title is required");
    }
    if (title.length > 120) {
      throw new ValidationException("title must not exceed 120 characters");
    }
    this._title = title;
    this._updatedAt = new Date();
  }

  /**
   * Update the description of the job posting.
   *
   * @param description - The new description. Must not be empty.
   * @throws {ValidationException} If validation fails.
   */
  updateDescription(description: string): void {
    if (!description || description.trim().length === 0) {
      throw new ValidationException("description is required");
    }
    this._description = description;
    this._updatedAt = new Date();
  }

  /**
   * Update the requirements of the job posting.
   *
   * @param requirements - The new requirements. Must not be empty.
   * @throws {ValidationException} If validation fails.
   */
  updateRequirements(requirements: string): void {
    if (!requirements || requirements.trim().length === 0) {
      throw new ValidationException("requirements is required");
    }
    this._requirements = requirements;
    this._updatedAt = new Date();
  }

  /**
   * Update the salary range of the job posting.
   *
   * @param salaryMin - The minimum salary (nullable).
   * @param salaryMax - The maximum salary (nullable).
   * @throws {ValidationException} If salaryMin > salaryMax (when both
   *                               are non-null), or if values are negative.
   */
  updateSalaryRange(salaryMin: number | null, salaryMax: number | null): void {
    if (salaryMin !== null && salaryMin < 0) {
      throw new ValidationException("salaryMin must not be negative");
    }
    if (salaryMax !== null && salaryMax < 0) {
      throw new ValidationException("salaryMax must not be negative");
    }
    if (salaryMin !== null && salaryMax !== null && salaryMin > salaryMax) {
      throw new ValidationException("salaryMin must not exceed salaryMax");
    }
    this._salaryMin = salaryMin;
    this._salaryMax = salaryMax;
    this._updatedAt = new Date();
  }

  /**
   * Update the location of the job posting.
   *
   * @param location - The new location. Must not be empty.
   * @throws {ValidationException} If validation fails.
   */
  updateLocation(location: string): void {
    if (!location || location.trim().length === 0) {
      throw new ValidationException("location is required");
    }
    this._location = location;
    this._updatedAt = new Date();
  }

  /**
   * Update the expiration date of the job posting.
   *
   * @param expiresAt - The new expiration date. Must be in the future.
   * @throws {ValidationException} If expiresAt is not after the
   *                               current time.
   */
  updateExpiresAt(expiresAt: Date): void {
    if (!expiresAt || expiresAt <= new Date()) {
      throw new ValidationException("expiresAt must be in the future");
    }
    this._expiresAt = expiresAt;
    this._updatedAt = new Date();
  }
}
