/**
 * Application domain entity — Rich Domain Model with State Machine.
 *
 * ═══════════════════════════════════════════════════════════════════
 * WHY RICH DOMAIN MODEL?
 * ═══════════════════════════════════════════════════════════════════
 *
 * Business rules that govern Application state transitions are
 * encapsulated inside the entity itself rather than scattered across
 * Use Cases. This prevents anemic domain models and ensures
 * consistency: every code path that changes application state
 * goes through the same validation, transition logic, and updatedAt
 * management.
 *
 * ═══════════════════════════════════════════════════════════════════
 * STATE MACHINE
 * ═══════════════════════════════════════════════════════════════════
 *
 *   APPLIED ────── review ──────────────→ UNDER_REVIEW
 *   UNDER_REVIEW ── scheduleInterview ───→ INTERVIEW
 *   INTERVIEW ──── offer ────────────────→ OFFERED
 *   OFFERED ────── hire ─────────────────→ HIRED
 *   UNDER_REVIEW ── reject ──────────────→ REJECTED
 *   INTERVIEW ──── reject ───────────────→ REJECTED
 *   APPLIED ────── withdraw ─────────────→ WITHDRAWN
 *   UNDER_REVIEW ── withdraw ────────────→ WITHDRAWN
 *   INTERVIEW ──── withdraw ─────────────→ WITHDRAWN
 *   REJECTED ───── reapply ──────────────→ APPLIED
 *
 * Each business method self-validates its allowed source state
 * directly — no global transition table is used.
 *
 * ═══════════════════════════════════════════════════════════════════
 * IMMUTABILITY NOTE
 * ═══════════════════════════════════════════════════════════════════
 *
 * Fields are private and only exposed via getters. State mutations
 * are performed exclusively through explicit business methods
 * (review, scheduleInterview, offer, hire, reject, withdraw, reapply)
 * which validate the transition and update `updatedAt` automatically.
 *
 * ═══════════════════════════════════════════════════════════════════
 *
 * @category Domain Entity
 */

import { ConflictException } from "../../../common/exceptions/conflict-exception";
import { ValidationException } from "../../../common/exceptions/validation-exception";

/**
 * Possible statuses for an Application.
 *
 * These represent the lifecycle of a job application from submission
 * through review, interview, offer, hire, or rejection/withdrawal.
 */
export enum ApplicationStatus {
  /** Initial state after submission. */
  APPLIED = "APPLIED",
  /** Application is being reviewed by the employer. */
  UNDER_REVIEW = "UNDER_REVIEW",
  /** Candidate has been invited for an interview. */
  INTERVIEW = "INTERVIEW",
  /** An offer has been extended to the candidate. */
  OFFERED = "OFFERED",
  /** Candidate has been hired. Terminal state. */
  HIRED = "HIRED",
  /** Application has been rejected. Can be reapplied. */
  REJECTED = "REJECTED",
  /** Application has been withdrawn by the candidate. Terminal state. */
  WITHDRAWN = "WITHDRAWN",
}

/**
 * Properties required to construct an Application entity.
 *
 * The `id` field is `string | null` because the entity may be created
 * before persistence (e.g. by ApplicationFactory). The actual ID
 * is generated by the database (Prisma cuid) when the entity is first
 * saved.
 */
export interface ApplicationProps {
  id: string | null;
  studentId: string;
  jobPostingId: string;
  cvId: string;
  status: ApplicationStatus;
  interviewId: string | null;
  offeredAt: Date | null;
  hiredAt: Date | null;
  rejectedAt: Date | null;
  rejectionReason: string | null;
  withdrawnAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export class Application {
  private _id: string | null;
  private _studentId: string;
  private _jobPostingId: string;
  private _cvId: string;
  private _status: ApplicationStatus;
  private _interviewId: string | null;
  private _offeredAt: Date | null;
  private _hiredAt: Date | null;
  private _rejectedAt: Date | null;
  private _rejectionReason: string | null;
  private _withdrawnAt: Date | null;
  private _createdAt: Date;
  private _updatedAt: Date;

  constructor(props: ApplicationProps) {
    this._id = props.id;
    this._studentId = props.studentId;
    this._jobPostingId = props.jobPostingId;
    this._cvId = props.cvId;
    this._status = props.status;
    this._interviewId = props.interviewId;
    this._offeredAt = props.offeredAt;
    this._hiredAt = props.hiredAt;
    this._rejectedAt = props.rejectedAt;
    this._rejectionReason = props.rejectionReason;
    this._withdrawnAt = props.withdrawnAt;
    this._createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  // ── Getters ──────────────────────────────────────────────────────

  get id(): string | null {
    return this._id;
  }

  get studentId(): string {
    return this._studentId;
  }

  get jobPostingId(): string {
    return this._jobPostingId;
  }

  get cvId(): string {
    return this._cvId;
  }

  get status(): ApplicationStatus {
    return this._status;
  }

  get interviewId(): string | null {
    return this._interviewId;
  }

  get offeredAt(): Date | null {
    return this._offeredAt;
  }

  get hiredAt(): Date | null {
    return this._hiredAt;
  }

  get rejectedAt(): Date | null {
    return this._rejectedAt;
  }

  get rejectionReason(): string | null {
    return this._rejectionReason;
  }

  get withdrawnAt(): Date | null {
    return this._withdrawnAt;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  // ── Business methods — State transitions ─────────────────────────

  /**
   * Move the application to UNDER_REVIEW.
   *
   * Transitions: APPLIED → UNDER_REVIEW
   *
   * @throws {ConflictException} If the current status is not APPLIED.
   */
  review(): void {
    if (this._status !== ApplicationStatus.APPLIED) {
      throw new ConflictException(
        `Cannot review: current status is ${this._status}, expected APPLIED`,
      );
    }
    this._status = ApplicationStatus.UNDER_REVIEW;
    this._updatedAt = new Date();
  }

  /**
   * Schedule an interview for this application.
   *
   * Transitions: UNDER_REVIEW → INTERVIEW
   *
   * @param interviewId - The ID of the interview to attach.
   * @throws {ConflictException} If the current status is not UNDER_REVIEW.
   * @throws {ValidationException} If interviewId is empty.
   */
  scheduleInterview(interviewId: string): void {
    if (this._status !== ApplicationStatus.UNDER_REVIEW) {
      throw new ConflictException(
        `Cannot schedule interview: current status is ${this._status}, expected UNDER_REVIEW`,
      );
    }
    if (!interviewId || interviewId.trim().length === 0) {
      throw new ValidationException("interviewId is required");
    }
    this._status = ApplicationStatus.INTERVIEW;
    this._interviewId = interviewId;
    this._updatedAt = new Date();
  }

  /**
   * Extend an offer to the candidate.
   *
   * Transitions: INTERVIEW → OFFERED
   *
   * @throws {ConflictException} If the current status is not INTERVIEW.
   */
  offer(): void {
    if (this._status !== ApplicationStatus.INTERVIEW) {
      throw new ConflictException(
        `Cannot offer: current status is ${this._status}, expected INTERVIEW`,
      );
    }
    this._status = ApplicationStatus.OFFERED;
    this._offeredAt = new Date();
    this._updatedAt = new Date();
  }

  /**
   * Mark the candidate as hired.
   *
   * Transitions: OFFERED → HIRED
   *
   * @throws {ConflictException} If the current status is not OFFERED.
   */
  hire(): void {
    if (this._status !== ApplicationStatus.OFFERED) {
      throw new ConflictException(
        `Cannot hire: current status is ${this._status}, expected OFFERED`,
      );
    }
    this._status = ApplicationStatus.HIRED;
    this._hiredAt = new Date();
    this._updatedAt = new Date();
  }

  /**
   * Reject the application.
   *
   * Transitions:
   *   - UNDER_REVIEW → REJECTED
   *   - INTERVIEW → REJECTED
   *
   * @param reason - The reason for rejection.
   * @throws {ConflictException} If the current status is not UNDER_REVIEW or INTERVIEW.
   * @throws {ValidationException} If reason is empty.
   */
  reject(reason: string): void {
    if (
      this._status !== ApplicationStatus.UNDER_REVIEW &&
      this._status !== ApplicationStatus.INTERVIEW
    ) {
      throw new ConflictException(
        `Cannot reject: current status is ${this._status}, expected UNDER_REVIEW or INTERVIEW`,
      );
    }
    if (!reason || reason.trim().length === 0) {
      throw new ValidationException("rejection reason is required");
    }
    this._status = ApplicationStatus.REJECTED;
    this._rejectedAt = new Date();
    this._rejectionReason = reason;
    this._updatedAt = new Date();
  }

  /**
   * Withdraw the application.
   *
   * Transitions:
   *   - APPLIED → WITHDRAWN
   *   - UNDER_REVIEW → WITHDRAWN
   *   - INTERVIEW → WITHDRAWN
   *
   * @throws {ConflictException} If the current status does not allow withdrawal.
   */
  withdraw(): void {
    if (
      this._status !== ApplicationStatus.APPLIED &&
      this._status !== ApplicationStatus.UNDER_REVIEW &&
      this._status !== ApplicationStatus.INTERVIEW
    ) {
      throw new ConflictException(
        `Cannot withdraw: current status is ${this._status}, expected APPLIED, UNDER_REVIEW, or INTERVIEW`,
      );
    }
    this._status = ApplicationStatus.WITHDRAWN;
    this._withdrawnAt = new Date();
    this._updatedAt = new Date();
  }

  /**
   * Reapply after a rejection.
   *
   * Transitions: REJECTED → APPLIED
   *
   * @throws {ConflictException} If the current status is not REJECTED.
   */
  reapply(): void {
    if (this._status !== ApplicationStatus.REJECTED) {
      throw new ConflictException(
        `Cannot reapply: current status is ${this._status}, expected REJECTED`,
      );
    }
    this._status = ApplicationStatus.APPLIED;
    this._rejectedAt = null;
    this._rejectionReason = null;
    this._updatedAt = new Date();
  }

  // ── Business methods — Field updates ─────────────────────────────

  /**
   * Change the CV attached to this application.
   *
   * @param cvId - The new CV ID. Must not be empty.
   * @throws {ValidationException} If cvId is empty.
   */
  changeCv(cvId: string): void {
    if (!cvId || cvId.trim().length === 0) {
      throw new ValidationException("cvId is required");
    }
    this._cvId = cvId;
    this._updatedAt = new Date();
  }

  /**
   * Attach an interview to this application.
   *
   * @param interviewId - The interview ID to attach. Must not be empty.
   * @throws {ValidationException} If interviewId is empty.
   */
  attachInterview(interviewId: string): void {
    if (!interviewId || interviewId.trim().length === 0) {
      throw new ValidationException("interviewId is required");
    }
    this._interviewId = interviewId;
    this._updatedAt = new Date();
  }

  /**
   * Detach the interview from this application.
   */
  detachInterview(): void {
    this._interviewId = null;
    this._updatedAt = new Date();
  }
}
