/**
 * CVMetadata domain entity — Rich Domain Model.
 *
 * ═══════════════════════════════════════════════════════════════════
 * WHY RICH DOMAIN MODEL?
 * ═══════════════════════════════════════════════════════════════════
 *
 * Business rules that govern CVMetadata state transitions are
 * encapsulated inside the entity itself rather than scattered across
 * Use Cases. This prevents anemic domain models and ensures
 * consistency: every code path that changes CV metadata state
 * goes through the same validation and updatedAt management logic.
 *
 * ═══════════════════════════════════════════════════════════════════
 * CONSTRUCTION INVARIANTS
 * ═══════════════════════════════════════════════════════════════════
 *
 * The constructor validates that required fields are provided and
 * that file constraints are met. This guarantees that a CVMetadata
 * entity can never exist in an invalid state:
 *
 *   - studentId must be a non-empty string
 *   - fileName must be a non-empty string
 *   - originalFileName must be a non-empty string
 *   - mimeType must be a non-empty string
 *   - storagePath must be a non-empty string
 *   - fileSize must be > 0
 *   - uploadedAt must be a valid Date
 *   - updatedAt must be a valid Date
 *
 * ═══════════════════════════════════════════════════════════════════
 * BUSINESS METHODS
 * ═══════════════════════════════════════════════════════════════════
 *
 * All mutations go through explicit business methods that enforce
 * preconditions and update `updatedAt` automatically:
 *
 *   markAsDefault()     → sets isDefault = true
 *   removeDefault()     → sets isDefault = false
 *   renameOriginalFile(newName)  → updates originalFileName
 *   moveStoragePath(newPath)     → updates storagePath
 *   updateMimeType(mimeType)     → updates mimeType
 *   updateFileSize(size)         → updates fileSize
 *   touch()                     → updates updatedAt only
 *
 * ═══════════════════════════════════════════════════════════════════
 * BUSINESS RULES BELONG TO USECASE
 * ═══════════════════════════════════════════════════════════════════
 *
 * The following rules are NOT validated in this entity:
 *   - Student existence
 *   - CV existence
 *   - Upload quotas / max upload limits
 *   - Virus scanning
 *   - Duplicate filename
 *   - Default uniqueness
 *   - Permission checks
 *
 * These are business flow concerns that belong to Use Cases.
 *
 * ═══════════════════════════════════════════════════════════════════
 * PERSISTENCE BELONGS TO REPOSITORY
 * ═══════════════════════════════════════════════════════════════════
 *
 * This entity depends ONLY on:
 *   - TypeScript built-ins
 *   - Custom BusinessException subclasses (domain-level concepts)
 *
 * It does NOT contain any persistence logic, Prisma references,
 * or database-specific code. The Repository is responsible for
 * mapping to/from the persistence model.
 *
 * ═══════════════════════════════════════════════════════════════════
 *
 * @category Domain Entity
 */

import { ValidationException } from "../../../../common/exceptions/validation-exception";
import { ConflictException } from "../../../../common/exceptions/conflict-exception";

/**
 * Properties required to construct a CVMetadata entity.
 *
 * The `id` field is `string | null` because the entity may be created
 * before persistence (e.g. by CVMetadataFactory). The actual ID is
 * generated by the database (Prisma cuid) when the entity is first saved.
 */
export interface CVMetadataProps {
  id: string | null;
  studentId: string;
  fileName: string;
  originalFileName: string;
  mimeType: string;
  fileSize: number;
  storagePath: string;
  isDefault: boolean;
  uploadedAt: Date;
  updatedAt: Date;
}

export class CVMetadata {
  private _id: string | null;
  private _studentId: string;
  private _fileName: string;
  private _originalFileName: string;
  private _mimeType: string;
  private _fileSize: number;
  private _storagePath: string;
  private _isDefault: boolean;
  private _uploadedAt: Date;
  private _updatedAt: Date;

  /**
   * Construct a CVMetadata entity.
   *
   * @param props - The properties required to build the entity.
   * @throws {ValidationException} If any construction invariant is violated.
   */
  constructor(props: CVMetadataProps) {
    if (!props.studentId || props.studentId.trim().length === 0) {
      throw new ValidationException("studentId is required");
    }

    if (!props.fileName || props.fileName.trim().length === 0) {
      throw new ValidationException("fileName is required");
    }

    if (!props.originalFileName || props.originalFileName.trim().length === 0) {
      throw new ValidationException("originalFileName is required");
    }

    if (!props.mimeType || props.mimeType.trim().length === 0) {
      throw new ValidationException("mimeType is required");
    }

    if (!props.storagePath || props.storagePath.trim().length === 0) {
      throw new ValidationException("storagePath is required");
    }

    if (props.fileSize <= 0) {
      throw new ValidationException("fileSize must be greater than 0");
    }

    if (!(props.uploadedAt instanceof Date) || isNaN(props.uploadedAt.getTime())) {
      throw new ValidationException("uploadedAt must be a valid Date");
    }

    if (!(props.updatedAt instanceof Date) || isNaN(props.updatedAt.getTime())) {
      throw new ValidationException("updatedAt must be a valid Date");
    }

    this._id = props.id;
    this._studentId = props.studentId;
    this._fileName = props.fileName;
    this._originalFileName = props.originalFileName;
    this._mimeType = props.mimeType;
    this._fileSize = props.fileSize;
    this._storagePath = props.storagePath;
    this._isDefault = props.isDefault;
    this._uploadedAt = props.uploadedAt;
    this._updatedAt = props.updatedAt;
  }

  // ── Getters ──────────────────────────────────────────────────────

  /** Unique identifier. `null` until persisted by the database. */
  get id(): string | null {
    return this._id;
  }

  /** ID of the student who owns this CV. */
  get studentId(): string {
    return this._studentId;
  }

  /** System-assigned file name (e.g. UUID-based). */
  get fileName(): string {
    return this._fileName;
  }

  /** Original file name as uploaded by the student. */
  get originalFileName(): string {
    return this._originalFileName;
  }

  /** MIME type of the uploaded file (e.g. "application/pdf"). */
  get mimeType(): string {
    return this._mimeType;
  }

  /** File size in bytes. */
  get fileSize(): number {
    return this._fileSize;
  }

  /** Storage path where the file is physically stored. */
  get storagePath(): string {
    return this._storagePath;
  }

  /** Whether this CV is the default CV for the student. */
  get isDefault(): boolean {
    return this._isDefault;
  }

  /** Timestamp of when the CV was uploaded. */
  get uploadedAt(): Date {
    return this._uploadedAt;
  }

  /** Timestamp of the last update. Updated automatically by every business method. */
  get updatedAt(): Date {
    return this._updatedAt;
  }

  // ── Business methods ─────────────────────────────────────────────

  /**
   * Mark this CV as the default CV.
   *
   * @throws {ConflictException} If this CV is already the default.
   */
  markAsDefault(): void {
    if (this._isDefault) {
      throw new ConflictException("CV is already marked as default");
    }
    this._isDefault = true;
    this._updatedAt = new Date();
  }

  /**
   * Remove the default status from this CV.
   *
   * @throws {ConflictException} If this CV is not currently the default.
   */
  removeDefault(): void {
    if (!this._isDefault) {
      throw new ConflictException("CV is not currently marked as default");
    }
    this._isDefault = false;
    this._updatedAt = new Date();
  }

  /**
   * Rename the original file name.
   *
   * @param newName - The new original file name. Must not be empty.
   * @throws {ValidationException} If `newName` is empty.
   */
  renameOriginalFile(newName: string): void {
    if (!newName || newName.trim().length === 0) {
      throw new ValidationException("newName is required");
    }
    this._originalFileName = newName;
    this._updatedAt = new Date();
  }

  /**
   * Move the storage path to a new location.
   *
   * @param newPath - The new storage path. Must not be empty.
   * @throws {ValidationException} If `newPath` is empty.
   */
  moveStoragePath(newPath: string): void {
    if (!newPath || newPath.trim().length === 0) {
      throw new ValidationException("newPath is required");
    }
    this._storagePath = newPath;
    this._updatedAt = new Date();
  }

  /**
   * Update the MIME type of this CV.
   *
   * @param mimeType - The new MIME type. Must not be empty.
   * @throws {ValidationException} If `mimeType` is empty.
   */
  updateMimeType(mimeType: string): void {
    if (!mimeType || mimeType.trim().length === 0) {
      throw new ValidationException("mimeType is required");
    }
    this._mimeType = mimeType;
    this._updatedAt = new Date();
  }

  /**
   * Update the file size of this CV.
   *
   * @param size - The new file size in bytes. Must be greater than 0.
   * @throws {ValidationException} If `size` is <= 0.
   */
  updateFileSize(size: number): void {
    if (size <= 0) {
      throw new ValidationException("fileSize must be greater than 0");
    }
    this._fileSize = size;
    this._updatedAt = new Date();
  }

  /**
   * Touch the entity — update only the `updatedAt` timestamp.
   *
   * Useful when a related entity changes and this CV metadata needs
   * its timestamp refreshed to reflect that it was indirectly modified.
   */
  touch(): void {
    this._updatedAt = new Date();
  }
}
